#pragma once

enum ObjectTypesAe : u8
{
    eContinuePoint = 0,
    ePathTransition = 1,
    eHoist = 2,
    eEdge = 3,
    eDeathDrop = 4,
    eDoor = 5,
    eShadow = 6,
    eLiftPoint = 7,
    eWellLocal = 8,
    eDove = 9,
    eRockSack = 10,
    eFallingItem = 11,
    ePullRingRope = 12,
    eBackgroundAnimation = 13,
    eTimedMine = 14,
    eSlig = 15,
    eSlog = 16,
    eSwitch = 17,
    eSecurityEye = 19,
    ePulley = 21,
    eAbeStart = 22,
    eWellExpress = 23,
    eMine = 24,
    eUxb = 25,
    eParamite = 26,
    eMovieStone = 27,
    eBirdPortal = 28,
    ePortalExit = 29,
    eTrapDoor = 30,
    eRollingBall = 31,
    eSligLeftBound = 32,
    eInvisibleZone = 33,
    eFootSwitch = 34,
    eSecurityOrb = 35,
    eMotionDetector = 36,
    eSligSpawner = 37,
    eElectricWall = 38,
    eLiftMover = 39,
    eMeatSack = 40,
    eScrab = 41,
    eScrabLeftBound = 43,
    eScrabRightBound = 44,
    eSligRightBound = 45,
    eSligPersist = 46,
    eEnemyStopper = 47,
    eInvisibleSwitch = 48,
    eMudokon = 49,
    eZSligCover = 50,
    eDoorFlame = 51,
    eMovingBomb = 52,
    eMenuController = 54,
    eTimerTrigger = 57,
    eSligVoiceLock = 58,
    eGrenadeMachine = 59,
    eLcdScreen = 60,
    eHandStone = 61,
    eCreditsController = 62,
    eNullObject1 = 63,
    eLcdStatusBoard = 64,
    eWorkWheelSyncer = 65,
    eMusic = 66,
    eLightEffect = 67,
    eSlogSpawner = 68,
    eDeathClock = 69,
    eGasEmitter = 71,
    eSlogHut = 72,
    eGlukkon = 73,
    eKillUnsavedMuds = 74,
    eSoftLanding = 75,
    eNullObject2 = 76,
    eWater = 77,
    eWorkWheel = 79,
    eLaughingGas = 81,
    eFlyingSlig = 82,
    eFleech = 83,
    eSlurgs = 84,
    eSlamDoor = 85,
    eLevelLoader = 86,
    eDemoSpawnPoint = 87,
    eTeleporter = 88,
    eSlurgSpawner = 89,
    eMineDrill = 90,
    eColorfulMeter = 91,
    eFlyingSligSpawner = 92,
    eMineCar = 93,
    eBoneBag = 94,
    eExplosionSet = 95,
    eMultiswitchController = 96,
    eRedGreenStatusLight = 97,
    eGhostLock = 98,
    eParamiteNet = 99,
    eAlarm = 100,
    eFartMachine = 101,
    eScrabSpawner = 102,
    eCrawlingSlig = 103,
    eSligGetPants = 104,
    eSligGetWings = 105,
    eGreeter = 106,
    eCrawlingSligButton = 107,
    eGlukkonSecurityFone = 108,
    eDoorBlocker = 109,
    eTorturedMudokon = 110,
    eTrainDoor = 111
};


namespace Oddlib { class MemoryStream; }
class Entity;

class AeEntityFactory
{
public:
    Entity Create(const Oddlib::Path::MapObject& object, EntityManager& entityManager, Oddlib::MemoryStream& ms);
};